CREATE EXTERNAL TABLE agrupa_cadenas  (
COD_GRUPO_N0 INT,
DES_GRUPO_N0 STRING,
COD_GRUPO_N1 INT,
DES_GRUPO_N1 STRING,
COD_GRUPO_N2 INT,
DES_GRUPO_N2 STRING,
COD_CADENA INT,
DES_CADENA STRING,
FORTA INT,
FECHA_INI STRING,
FECHA_FIN STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ","
LOCATION '/user/julio/mediaset/agrupa_cadenas';
