SELECT A.nom_dia,
       A.cod_mes,
       A.nom_mes,
       A.cod_anio,
       A.cod_periodo,
       A.nom_periodo,
       A.cod_mes_com,
       A.nom_mes_com,
       A.cod_day_part,
       A.des_day_part,
       A.cod_cadena,
       A.nom_cadena,
       A.cod_anuncio,
       A.nom_anuncio,
       A.cod_anunciante_subsidiario,
       A.nom_anunciante_subsidiario,
       A.cod_sect_geog,
       A.nom_sect_geog,
       A.cod_tipologia,
       A.nom_tipologia,
       A.cod_comunicacion,
       A.nom_comunicacion,
       A.cod_producto,
       A.nom_producto,
       A.cod_grupo,
       A.nom_grupo,
       A.cod_sector,
       A.nom_sector,
       A.duracion,
       A.cod_pos_pb3,
       A.num_spots_pb3,
       A.cod_posicion_pb3,
       A.nom_posicion_pb3,
       A.cod_cualitativo,
       A.nom_cualitativo,
       A.cod_ejecutivo,
       A.nom_ejecutivo,
       A.cod_subdivision,
       A.nom_subdivision,
       A.cod_division,
       A.nom_division,
       A.cod_area,
       A.nom_area,
       A.cod_dir_comercial,
       A.nom_dir_comercial,
       A.cod_dir_general,
       A.nom_dir_general,
       A.cod_empresa,
       A.nom_empresa,
       A.cod_marca,
       A.nom_marca,
       A.cod_anunc,
       A.nom_anunc,
       A.cod_holding,
       A.nom_holding,
       A.cod_central,
       A.nom_central,
       A.cod_grupo_cent,
       A.nom_grupo_cent,
       A.cod_marca_h,
       A.nom_marca_h,
       A.cod_anunc_h,
       A.nom_anunc_h,
       A.cod_target_generico,
       A.nom_target_generico,
       A.cod_fg_anun_local,
       A.nom_fg_anun_local,
       A.cod_fg_televenta,
       A.nom_fg_televenta,
       A.cod_fg_pub_compartida,
       A.nom_fg_pub_compartida,
       A.cod_fg_autopromo,
       A.nom_fg_autopromo,
       SUM(A.grps_20) AS SUMAGRPS_20,
       B.IIEE_NIV1,
       B.IIEE_NIV2,
       B.IIEE_NIV3,
       IIF(COD_ANUNCIO IN
             (SELECT COD_ANUNCIO
              FROM FCTS_MERCADO_LINEAL
              WHERE NOM_CADENA IN
                  (SELECT DES_CADENA
                   FROM DIM_AGRUPA_CADENAS
                   WHERE DES_GRUPO="MEDIASET")), 1, 0) AS COD_CAMP_MED,
       IIF(cod_anunciante_subsidiario IN
             (SELECT cod_anunciante_subsidiario
              FROM FCTS_MERCADO_LINEAL
              WHERE NOM_CADENA IN
                  (SELECT DES_CADENA
                   FROM DIM_AGRUPA_CADENAS
                   WHERE DES_GRUPO="MEDIASET")), 1, 0) AS COD_ANUNC_MED,
       "" AS COD_EVENTO,
       IIF(NOM_CADENA IN
             (SELECT DES_CADENA
              FROM DIM_AGRUPA_CADENAS
              WHERE DES_GRUPO="AUTONOMICAS"), 1, 0) AS COD_CAD_AUTONOMICA,
       IIF(NOM_CADENA IN
             (SELECT DES_CADENA
              FROM DIM_AGRUPA_CADENAS
              WHERE FORTA=1), 1, 0) AS COD_CAD_FORTA,
       IIF(NOM_CADENA IN
             (SELECT DES_CADENA
              FROM DIM_AGRUPA_CADENAS
              WHERE DES_GRUPO="Módulo BOING"), 1, 0) AS COD_CAD_BOING
FROM FCTS_MERCADO_LINEAL AS A
INNER JOIN DIM_IIEE AS B ON (A.NOM_TIPOLOGIA=B.NOM_TIPOLOGIA)
AND (A.NOM_COMUNICACION = B.NOM_COMUNICACION)
GROUP BY A.nom_dia,
         A.cod_mes,
         A.nom_mes,
         A.cod_anio,
         A.cod_periodo,
         A.nom_periodo,
         A.cod_mes_com,
         A.nom_mes_com,
         A.cod_day_part,
         A.des_day_part,
         A.cod_cadena,
         A.nom_cadena,
         A.cod_anuncio,
         A.nom_anuncio,
         A.cod_anunciante_subsidiario,
         A.nom_anunciante_subsidiario,
         A.cod_sect_geog,
         A.nom_sect_geog,
         A.cod_tipologia,
         A.nom_tipologia,
         A.cod_comunicacion,
         A.nom_comunicacion,
         A.cod_producto,
         A.nom_producto,
         A.cod_grupo,
         A.nom_grupo,
         A.cod_sector,
         A.nom_sector,
         A.duracion,
         A.cod_pos_pb3,
         A.num_spots_pb3,
         A.cod_posicion_pb3,
         A.nom_posicion_pb3,
         A.cod_cualitativo,
         A.nom_cualitativo,
         A.cod_ejecutivo,
         A.nom_ejecutivo,
         A.cod_subdivision,
         A.nom_subdivision,
         A.cod_division,
         A.nom_division,
         A.cod_area,
         A.nom_area,
         A.cod_dir_comercial,
         A.nom_dir_comercial,
         A.cod_dir_general,
         A.nom_dir_general,
         A.cod_empresa,
         A.nom_empresa,
         A.cod_marca,
         A.nom_marca,
         A.cod_anunc,
         A.nom_anunc,
         A.cod_holding,
         A.nom_holding,
         A.cod_central,
         A.nom_central,
         A.cod_grupo_cent,
         A.nom_grupo_cent,
         A.cod_marca_h,
         A.nom_marca_h,
         A.cod_anunc_h,
         A.nom_anunc_h,
         A.cod_target_generico,
         A.nom_target_generico,
         A.cod_fg_anun_local,
         A.nom_fg_anun_local,
         A.cod_fg_televenta,
         A.nom_fg_televenta,
         A.cod_fg_pub_compartida,
         A.nom_fg_pub_compartida,
         A.cod_fg_autopromo,
         A.nom_fg_autopromo,
         B.IIEE_NIV1,
         B.IIEE_NIV2,
         B.IIEE_NIV3;
